#include "instruction_sets.H"

#include "instructions.H"

const struct instruction instruction_set[] =
{
	{ "NOP",				1, 4,  true,	instruction_00 },
	{ "LD BC, $%04x",		3, 12, true,	instruction_01 },
	{ "LD (BC), A",			1, 8,  true,	instruction_02 },
	{ "INC BC",				1, 8,  true,	instruction_03 },
	{ "INC B",				1, 4,  true,	instruction_04 },
	{ "DEC B",				1, 4,  true,	instruction_05 },
	{ "LD B, $%04x",		2, 8,  true,	instruction_06 },
	{ "RLCA",				1, 4,  true,	instruction_07 },
	{ "LD $%04x, SP",		3, 20, true,	instruction_08 },
	{ "ADD HL, BC",			1, 8,  true,	instruction_09 },
	{ "LD A, (BC)",			1, 8,  true,	instruction_0a },
	{ "DEC BC",				1, 8,  true,	instruction_0b },
	{ "INC C",				1, 8,  true,	instruction_0c },
	{ "DEC C",				1, 4,  true,	instruction_0d },
	{ "LD C, $%04x",		2, 8,  true,	instruction_0e },
	{ "RRCA",				1, 4,  true,	instruction_0f },
	{ "STOP 0",				1, 4,  true,	instruction_10 },
	{ "LD DE, $%04x",		3, 12, true,	instruction_11 },
	{ "LD (DE), A",			1, 8,  true,	instruction_12 },
	{ "INC DE",				1, 8,  true,	instruction_13 },
	{ "INC D",				1, 4,  true,	instruction_14 },
	{ "DEC D",				1, 4,  true,	instruction_15 },
	{ "LD D, $%04x",		2, 8,  true,	instruction_16 },
	{ "RLA",				1, 4,  true,	instruction_17 },
	{ "JR $%04x",			2, 12, true,	instruction_18 },
	{ "ADD HL, DE",			1, 8,  true,	instruction_19 },
	{ "LD A, (DE)",			1, 8,  true,	instruction_1a },
	{ "DEC DE",				1, 8,  true,	instruction_1b },
	{ "INC E",				1, 4,  true,	instruction_1c },
	{ "DEC E",				1, 4,  true,	instruction_1d },
	{ "LD E, $%04x",		2, 8,  true,	instruction_1e },
	{ "RRA",				1, 4,  true,	instruction_1f },
	{ "JR NZ, $%04x",		2, 12, true,	instruction_20 },
	{ "LD HL, $%04x",		3, 12, true,	instruction_21 },
	{ "LD (HL+), A",		1, 8,  true,	instruction_22 },
	{ "INC HL",				1, 8,  true,	instruction_23 },
	{ "INC H",				1, 4,  true,	instruction_24 },
	{ "DEC H",				1, 4,  true,	instruction_25 },
	{ "LD H, $%04x",		2, 8,  true,	instruction_26 },
	{ "DAA",				1, 4,  true,	instruction_27 },
	{ "JR z, $%04x",		2, 12, true,	instruction_28 },
	{ "ADD HL, HL",			1, 8,  true,	instruction_29 },
	{ "LD A, (HL+)",		1, 8,  true,	instruction_2a },
	{ "DEC HL",				1, 8,  true,	instruction_2b },
	{ "INC L",				1, 4,  true,	instruction_2c },
	{ "DEC L",				1, 4,  true,	instruction_2d },
	{ "LD L, $%04x",		2, 8,  true,	instruction_2e },
	{ "CPL",				1, 4,  true,	instruction_2f },
	{ "JR NC, $%04x",		2, 12, true,	instruction_30 },
	{ "LD SP, $%04x",		3, 12, true,	instruction_31 },
	{ "LD (HL-), A",		1, 8,  true,	instruction_32 },
	{ "INC SP",				1, 8,  true,	instruction_33 },
	{ "INC (HL)",			1, 12, true,	instruction_34 },
	{ "DEC (HL)",			1, 12, true,	instruction_35 },
	{ "LD (HL), $%04x",		2, 12, true,	instruction_36 },
	{ "SCF",				1, 4,  true,	instruction_37 },
	{ "JR C, $%04x",		2, 12, true,	instruction_38 },
	{ "ADD HL, SP",			1, 8,  true,	instruction_39 },
	{ "LD A, (HL-)",		1, 8,  true,	instruction_3a },
	{ "DEC SP",				1, 8,  true,	instruction_3b },
	{ "INC A",				1, 4,  true,	instruction_3c },
	{ "DEC A",				1, 4,  true,	instruction_3d },
	{ "LD A, $%04x",		2, 8,  true,	instruction_3e },
	{ "CCF",				1, 4,  true,	instruction_3f },
	{ "LD B, B",			1, 4,  true,	instruction_40 },
	{ "LD B, C",			1, 4,  true,	instruction_41 },
	{ "LD B, D",			1, 4,  true,	instruction_42 },
	{ "LD B, E",			1, 4,  true,	instruction_43 },
	{ "LD B, H",			1, 4,  true,	instruction_44 },
	{ "LD B, L",			1, 4,  true,	instruction_45 },
	{ "LD B, (HL)",			1, 8,  true,	instruction_46 },
	{ "LD B, A",			1, 4,  true,	instruction_47 },
	{ "LD C, B",			1, 4,  true,	instruction_48 },
	{ "LD C, C",			1, 4,  true,	instruction_49 },
	{ "LD C, D",			1, 4,  true,	instruction_4a },
	{ "LD C, E",			1, 4,  true,	instruction_4b },
	{ "LD C, H",			1, 4,  true,	instruction_4c },
	{ "LD C, L",			1, 4,  true,	instruction_4d },
	{ "LD C, (HL)",			1, 8,  true,	instruction_4e },
	{ "LD C, A",			1, 4,  true,	instruction_4f },
	{ "LD D, B",			1, 4,  true,	instruction_50 },
	{ "LD D, C",			1, 4,  true,	instruction_51 },
	{ "LD D, D",			1, 4,  true,	instruction_52 },
	{ "LD D, E",			1, 4,  true,	instruction_53 },
	{ "LD D, H",			1, 4,  true,	instruction_54 },
	{ "LD D, L",			1, 4,  true,	instruction_55 },
	{ "LD D, (HL)",			1, 8,  true,	instruction_56 },
	{ "LD D, A",			1, 4,  true,	instruction_57 },
	{ "LD E, B",			1, 4,  true,	instruction_58 },
	{ "LD E, C",			1, 4,  true,	instruction_59 },
	{ "LD E, D",			1, 4,  true,	instruction_5a },
	{ "LD E, E",			1, 4,  true,	instruction_5b },
	{ "LD E, H",			1, 4,  true,	instruction_5c },
	{ "LD E, L",			1, 4,  true,	instruction_5d },
	{ "LD E, (HL)",			1, 8,  true,	instruction_5e },
	{ "LD E, A",			1, 4,  true,	instruction_5f },
	{ "LD H, B",			1, 4,  true,	instruction_60 },
	{ "LD H, C",			1, 4,  true,	instruction_61 },
	{ "LD H, D",			1, 4,  true,	instruction_62 },
	{ "LD H, E",			1, 4,  true,	instruction_63 },
	{ "LD H, H",			1, 4,  true,	instruction_64 },
	{ "LD H, L",			1, 4,  true,	instruction_65 },
	{ "LD H, (HL)",			1, 8,  true,	instruction_66 },
	{ "LD H, A",			1, 4,  true,	instruction_67 },
	{ "LD L, B",			1, 4,  true,	instruction_68 },
	{ "LD L, C",			1, 4,  true,	instruction_69 },
	{ "LD L, D",			1, 4,  true,	instruction_6a },
	{ "LD L, E",			1, 4,  true,	instruction_6b },
	{ "LD L, H",			1, 4,  true,	instruction_6c },
	{ "LD L, L",			1, 4,  true,	instruction_6d },
	{ "LD L, (HL)",			1, 8,  true,	instruction_6e },
	{ "LD L, A",			1, 8,  true,	instruction_6f },
	{ "LD (HL), B",			1, 8,  true,	instruction_70 },
	{ "LD (HL), C",			1, 8,  true,	instruction_71 },
	{ "LD (HL), D",			1, 8,  true,	instruction_72 },
	{ "LD (HL), E",			1, 8,  true,	instruction_73 },
	{ "LD (HL), H",			1, 8,  true,	instruction_74 },
	{ "LD (HL), L",			1, 8,  true,	instruction_75 },
	{ "HALT",				1, 4,  true,	instruction_76 },
	{ "LD (HL), A",			1, 8,  true,	instruction_77 },
	{ "LD A, B",			1, 4,  true,	instruction_78 },
	{ "LD A, C",			1, 4,  true,	instruction_79 },
	{ "LD A, D",			1, 4,  true,	instruction_7a },
	{ "LD A, E",			1, 4,  true,	instruction_7b },
	{ "LD A, H",			1, 4,  true,	instruction_7c },
	{ "LD A, L",			1, 4,  true,	instruction_7d },
	{ "LD A, (HL)",			1, 8,  true,	instruction_7e },
	{ "LD A, A",			1, 4,  true,	instruction_7f },
	{ "ADD A, B",			1, 4,  true,	instruction_80 },
	{ "ADD A, C",			1, 4,  true,	instruction_81 },
	{ "ADD A, D",			1, 4,  true,	instruction_82 },
	{ "ADD A, E",			1, 4,  true,	instruction_83 },
	{ "ADD A, H",			1, 4,  true,	instruction_84 },
	{ "ADD A, L",			1, 4,  true,	instruction_85 },
	{ "ADD A, (HL)",		1, 8,  true,	instruction_86 },
	{ "ADD A, A",			1, 4,  true,	instruction_87 },
	{ "ADC A, B",			1, 4,  true,	instruction_88 },
	{ "ADC A, C",			1, 4,  true,	instruction_89 },
	{ "ADC A, D",			1, 4,  true,	instruction_8a },
	{ "ADC A, E",			1, 4,  true,	instruction_8b },
	{ "ADC A, H",			1, 4,  true,	instruction_8c },
	{ "ADC A, L",			1, 4,  true,	instruction_8d },
	{ "ADC A, (HL)",		1, 8,  true,	instruction_8e },
	{ "ADC A, A",			1, 4,  true,	instruction_8f },
	{ "SUB B",				1, 4,  true,	instruction_90 },
	{ "SUB C",				1, 4,  true,	instruction_91 },
	{ "SUB D",				1, 4,  true,	instruction_92 },
	{ "SUB E",				1, 4,  true,	instruction_93 },
	{ "SUB H",				1, 4,  true,	instruction_94 },
	{ "SUB L",				1, 4,  true,	instruction_95 },
	{ "SUB (HL)",			1, 8,  true,	instruction_96 },
	{ "SUB A",				1, 4,  true,	instruction_97 },
	{ "SBC A, B",			1, 4,  true,	instruction_98 },
	{ "SBC A, C",			1, 4,  true,	instruction_99 },
	{ "SBC A, D",			1, 4,  true,	instruction_9a },
	{ "SBC A, E",			1, 4,  true,	instruction_9b },
	{ "SBC A, H",			1, 4,  true,	instruction_9c },
	{ "SBC A, L",			1, 4,  true,	instruction_9d },
	{ "SBC A, (HL)",		1, 8,  true,	instruction_9e },
	{ "SBC A, A",			1, 4,  true,	instruction_9f },
	{ "AND B",				1, 4,  true,	instruction_a0 },
	{ "AND C",				1, 4,  true,	instruction_a1 },
	{ "AND D",				1, 4,  true,	instruction_a2 },
	{ "AND E",				1, 4,  true,	instruction_a3 },
	{ "AND H",				1, 4,  true,	instruction_a4 },
	{ "AND L",				1, 4,  true,	instruction_a5 },
	{ "AND (HL)",			1, 8,  true,	instruction_a6 },
	{ "AND A",				1, 4,  true,	instruction_a7 },
	{ "XOR B",				1, 4,  true,	instruction_a8 },
	{ "XOR C",				1, 4,  true,	instruction_a9 },
	{ "XOR D",				1, 4,  true,	instruction_aa },
	{ "XOR E",				1, 4,  true,	instruction_ab },
	{ "XOR H",				1, 4,  true,	instruction_ac },
	{ "XOR L",				1, 4,  true,	instruction_ad },
	{ "XOR (HL)",			1, 8,  true,	instruction_ae },
	{ "XOR A",				1, 4,  true,	instruction_af },
	{ "OR B",				1, 4,  true,	instruction_b0 },
	{ "OR C",				1, 4,  true,	instruction_b1 },
	{ "OR D",				1, 4,  true,	instruction_b2 },
	{ "OR E",				1, 4,  true,	instruction_b3 },
	{ "OR H",				1, 4,  true,	instruction_b4 },
	{ "OR L",				1, 4,  true,	instruction_b5 },
	{ "OR (HL)",			1, 8,  true,	instruction_b6 },
	{ "OR A",				1, 4,  true,	instruction_b7 },
	{ "CP B",				1, 4,  true,	instruction_b8 },
	{ "CP C",				1, 4,  true,	instruction_b9 },
	{ "CP D",				1, 4,  true,	instruction_ba },
	{ "CP E",				1, 4,  true,	instruction_bb },
	{ "CP H",				1, 4,  true,	instruction_bc },
	{ "CP L",				1, 4,  true,	instruction_bd },
	{ "CP (HL)",			1, 8,  true,	instruction_be },
	{ "CP A",				1, 4,  true,	instruction_bf },
	{ "RET NZ",				1, 20, false,	instruction_c0 },
	{ "POP BC",				1, 12, true,	instruction_c1 },
	{ "JP NZ, $%04x",		3, 16, false,	instruction_c2 },
	{ "JP $%04x",			3, 16, false,	instruction_c3 },
	{ "CALL NZ, $%04x",		3, 24, false,	instruction_c4 },
	{ "PUSH BC",			1, 16, true,	instruction_c5 },
	{ "ADD A, $%04x",		2, 8,  true,	instruction_c6 },
	{ "RST 00H",			1, 16, true,	instruction_c7 },
	{ "RET z",				1, 20, false,	instruction_c8 },
	{ "RET",				1, 16, false,	instruction_c9 },
	{ "JP z, $%04x",		3, 16, false,	instruction_ca },
	{ "PREFIX CB",			1, 4,  false,	instruction_cb },
	{ "CALL z, $%04x",		3, 24, false,	instruction_cc },
	{ "CALL $%04x",			3, 24, false,	instruction_cd },
	{ "ADC A, $%04x",		2, 8,  true,	instruction_ce },
	{ "RST 08H",			1, 16, true,	instruction_cf },
	{ "RET NC",				1, 20, false,	instruction_d0 },
	{ "POP DE",				1, 12, true,	instruction_d1 },
	{ "JP NC, $%04x",		3, 16, false,	instruction_d2 },
	{ "",					0, 0,  false,	NULL },	   
	{ "CALL NC, $%04x",		3, 24, true,	instruction_d4 },
	{ "PUSH DE",			1, 16, true,	instruction_d5 },
	{ "SUB $%04x",			2, 8,  true,	instruction_d6 },
	{ "RST 10H",			1, 16, true,	instruction_d7 },
	{ "RET C",				1, 20, false,	instruction_d8 },
	{ "RETI",				1, 16, false,	instruction_d9 },
	{ "JP C, $%04x",		3, 16, false,	instruction_da },
	{ "",					0, 0,  false,	NULL },	   
	{ "CALL C, $%04x",		3, 24, false,	instruction_dc },
	{ "",					0, 0,  false,	NULL },	   
	{ "SBC A, $%04x",		2, 8,  true,	instruction_de },
	{ "RST 18H",			1, 16, true,	instruction_df },
	{ "LDH ($%04x), A",		2, 12, true,	instruction_e0 },
	{ "POP HL",				1, 12, true,	instruction_e1 },
	{ "LD ($FF00+C), A",	1, 8,  true,	instruction_e2 },
	{ "",					0, 0,  false,	NULL },	   
	{ "",					0, 0,  false,	NULL },	   
	{ "PUSH HL",			1, 16, true,	instruction_e5 },
	{ "AND $%04x",			2, 8,  true,	instruction_e6 },
	{ "RST 20H",			1, 16, true,	instruction_e7 },
	{ "ADD SP, $%04x",		2, 16, true,	instruction_e8 },
	{ "JP (HL)",			1, 4,  false,	instruction_e9 },
	{ "LD ($%04x), A",		3, 16, true,	instruction_ea },
	{ "",					0, 0,  false,	NULL },	   
	{ "",					0, 0,  false,	NULL },	   
	{ "",					0, 0,  false,	NULL },	   
	{ "XOR $%04x",			2, 8,  true,	instruction_ee },
	{ "RST 28H",			1, 16, true,	instruction_ef },
	{ "LDH A, ($%04x)",		2, 12, true,	instruction_f0 },
	{ "POP AF",				1, 12, true,	instruction_f1 },
	{ "LD A, (C)",			2, 8,  true,	instruction_f2 },
	{ "DI",					1, 4,  true,	instruction_f3 },
	{ "",					0, 0,  false,	NULL },	   
	{ "PUSH af",			1, 16, true,	instruction_f5 },
	{ "OR $%04x",			2, 8,  true,	instruction_f6 },
	{ "RST 30H",			1, 16, true,	instruction_f7 },
	{ "LD HL, SP + $%04x",	2, 12, true,	instruction_f8 },
	{ "LD SP, HL",			1, 8,  true,	instruction_f9 },
	{ "LD A, ($%04x)",		3, 16, true,	instruction_fa },
	{ "EI",					1, 4,  true,	instruction_fb },
	{ "",					0, 0,  false,	NULL },	   
	{ "",					0, 0,  false,	NULL },	   
	{ "CP $%04x",			2, 8,  true,	instruction_fe },
	{ "RST 38H",			1, 16, false,	instruction_ff }
};

const struct instruction extended_instruction_set[] =
{
	"RLC B",		2, 8,	true, extended_instruction_00,
	"RLC C",		2, 8,	true, extended_instruction_01,
	"RLC D",		2, 8,	true, extended_instruction_02,
	"RLC E",		2, 8,	true, extended_instruction_03,
	"RLC H",		2, 8,	true, extended_instruction_04,
	"RLC L",		2, 8,	true, extended_instruction_05,
	"RLC (HL)",		2, 16,	true, extended_instruction_06,
	"RLC A",		2, 8,	true, extended_instruction_07,
	"RRC B",		2, 8,	true, extended_instruction_08,
	"RRC C",		2, 8,	true, extended_instruction_09,
	"RRC D",		2, 8,	true, extended_instruction_0a,
	"RRC E",		2, 8,	true, extended_instruction_0b,
	"RRC H",		2, 8,	true, extended_instruction_0c,
	"RRC B",		2, 8,	true, extended_instruction_0d,
	"RRC (HL)",		2, 16,	true, extended_instruction_0e,
	"RRC A",		2, 8,	true, extended_instruction_0f,
	"RL B",			2, 8,	true, extended_instruction_10,
	"RL C",			2, 8,	true, extended_instruction_11,
	"RL D",			2, 8,	true, extended_instruction_12,
	"RL E",			2, 8,	true, extended_instruction_13,
	"RL H",			2, 8,	true, extended_instruction_14,
	"RL L",			2, 8,	true, extended_instruction_15,
	"RL (HL)",		2, 16,	true, extended_instruction_16,
	"RL A",			2, 8,	true, extended_instruction_17,
	"RR B",			2, 8,	true, extended_instruction_18,
	"RR C",			2, 8,	true, extended_instruction_19,
	"RR D",			2, 8,	true, extended_instruction_1a,
	"RR E",			2, 8,	true, extended_instruction_1b,
	"RR H",			2, 8,	true, extended_instruction_1c,
	"RR L",			2, 8,	true, extended_instruction_1d,
	"RR (HL)",		2, 16,	true, extended_instruction_1e,
	"RR A",			2, 8,	true, extended_instruction_1f,
	"SLA B",		2, 8,	true, extended_instruction_20,
	"SLA C",		2, 8,	true, extended_instruction_21,
	"SLA D",		2, 8,	true, extended_instruction_22,
	"SLA E",		2, 8,	true, extended_instruction_23,
	"SLA H",		2, 8,	true, extended_instruction_24,
	"SLA L",		2, 8,	true, extended_instruction_25,
	"SLA (HL)",		2, 16,	true, extended_instruction_26,
	"SLA A",		2, 8,	true, extended_instruction_27,
	"SRA B",		2, 8,	true, extended_instruction_28,
	"SRA C",		2, 8,	true, extended_instruction_29,
	"SRA D",		2, 8,	true, extended_instruction_2a,
	"SRA E",		2, 8,	true, extended_instruction_2b,
	"SRA H",		2, 8,	true, extended_instruction_2c,
	"SRA L",		2, 8,	true, extended_instruction_2d,
	"SRA (HL)",		2, 16,	true, extended_instruction_2e,
	"SRA A",		2, 8,	true, extended_instruction_2f,
	"SWAP B",		2, 8,	true, extended_instruction_30,
	"SWAP C",		2, 8,	true, extended_instruction_31,
	"SWAP D",		2, 8,	true, extended_instruction_32,
	"SWAP E",		2, 8,	true, extended_instruction_33,
	"SWAP H",		2, 8,	true, extended_instruction_34,
	"SWAP L",		2, 8,	true, extended_instruction_35,
	"SWAP (HL)",	2, 16,	true, extended_instruction_36,
	"SWAP A",		2, 8,	true, extended_instruction_37,
	"SRA B",		2, 8,	true, extended_instruction_38,
	"SRA C",		2, 8,	true, extended_instruction_39,
	"SRA D",		2, 8,	true, extended_instruction_3a,
	"SRA E",		2, 8,	true, extended_instruction_3b,
	"SRA H",		2, 8,	true, extended_instruction_3c,
	"SRA L",		2, 8,	true, extended_instruction_3d,
	"SRA (HL)",		2, 16,	true, extended_instruction_3e,
	"SRA A",		2, 8,	true, extended_instruction_3f,
	"BIT 0, B",		2, 8,	true, extended_instruction_40,
	"BIT 0, C",		2, 8,	true, extended_instruction_41,
	"BIT 0, D",		2, 8,	true, extended_instruction_42,
	"BIT 0, E",		2, 8,	true, extended_instruction_43,
	"BIT 0, H",		2, 8,	true, extended_instruction_44,
	"BIT 0, L",		2, 8,	true, extended_instruction_45,
	"BIT 0, (HL)",	2, 16,	true, extended_instruction_46,
	"BIT 0, A",		2, 8,	true, extended_instruction_47,
	"BIT 1, B",		2, 8,	true, extended_instruction_48,
	"BIT 1, C",		2, 8,	true, extended_instruction_49,
	"BIT 1, D",		2, 8,	true, extended_instruction_4a,
	"BIT 1, E",		2, 8,	true, extended_instruction_4b,
	"BIT 1, H",		2, 8,	true, extended_instruction_4c,
	"BIT 1, L",		2, 8,	true, extended_instruction_4d,
	"BIT 1, (HL)",	2, 16,	true, extended_instruction_4e,
	"BIT 1, A",		2, 8,	true, extended_instruction_4f,
	"BIT 2, B",		2, 8,	true, extended_instruction_50,
	"BIT 2, C",		2, 8,	true, extended_instruction_51,
	"BIT 2, D",		2, 8,	true, extended_instruction_52,
	"BIT 2, E",		2, 8,	true, extended_instruction_53,
	"BIT 2, H",		2, 8,	true, extended_instruction_54,
	"BIT 2, L",		2, 8,	true, extended_instruction_55,
	"BIT 2, (HL)",	2, 16,	true, extended_instruction_56,
	"BIT 2, A",		2, 8,	true, extended_instruction_57,
	"BIT 3, B",		2, 8,	true, extended_instruction_58,
	"BIT 3, C",		2, 8,	true, extended_instruction_59,
	"BIT 3, D",		2, 8,	true, extended_instruction_5a,
	"BIT 3, E",		2, 8,	true, extended_instruction_5b,
	"BIT 3, H",		2, 8,	true, extended_instruction_5c,
	"BIT 3, L",		2, 8,	true, extended_instruction_5d,
	"BIT 3, (HL)",	2, 16,	true, extended_instruction_5e,
	"BIT 3, A",		2, 8,	true, extended_instruction_5f,
	"BIT 4, B",		2, 8,	true, extended_instruction_60,
	"BIT 4, C",		2, 8,	true, extended_instruction_61,
	"BIT 4, D",		2, 8,	true, extended_instruction_62,
	"BIT 4, E",		2, 8,	true, extended_instruction_63,
	"BIT 4, H",		2, 8,	true, extended_instruction_64,
	"BIT 4, L",		2, 8,	true, extended_instruction_65,
	"BIT 4, (HL)",	2, 16,	true, extended_instruction_66,
	"BIT 4, A",		2, 8,	true, extended_instruction_67,
	"BIT 5, B",		2, 8,	true, extended_instruction_68,
	"BIT 5, C",		2, 8,	true, extended_instruction_69,
	"BIT 5, D",		2, 8,	true, extended_instruction_6a,
	"BIT 5, E",		2, 8,	true, extended_instruction_6b,
	"BIT 5, H",		2, 8,	true, extended_instruction_6c,
	"BIT 5, L",		2, 8,	true, extended_instruction_6d,
	"BIT 5, (HL)",	2, 16,	true, extended_instruction_6e,
	"BIT 5, A",		2, 8,	true, extended_instruction_6f,
	"BIT 6, B",		2, 8,	true, extended_instruction_70,
	"BIT 6, C",		2, 8,	true, extended_instruction_71,
	"BIT 6, D",		2, 8,	true, extended_instruction_72,
	"BIT 6, E",		2, 8,	true, extended_instruction_73,
	"BIT 6, H",		2, 8,	true, extended_instruction_74,
	"BIT 6, L",		2, 8,	true, extended_instruction_75,
	"BIT 6, (HL)",	2, 16,	true, extended_instruction_76,
	"BIT 6, A",		2, 8,	true, extended_instruction_77,
	"BIT 7, B",		2, 8,	true, extended_instruction_78,
	"BIT 7, C",		2, 8,	true, extended_instruction_79,
	"BIT 7, D",		2, 8,	true, extended_instruction_7a,
	"BIT 7, E",		2, 8,	true, extended_instruction_7b,
	"BIT 7, H",		2, 8,	true, extended_instruction_7c,
	"BIT 7, L",		2, 8,	true, extended_instruction_7d,
	"BIT 7, (HL)",	2, 16,	true, extended_instruction_7e,
	"BIT 7, A",		2, 8,	true, extended_instruction_7f,
	"RES 0, B",		2, 8,	true, extended_instruction_80,
	"RES 0, C",		2, 8,	true, extended_instruction_81,
	"RES 0, D",		2, 8,	true, extended_instruction_82,
	"RES 0, E",		2, 8,	true, extended_instruction_83,
	"RES 0, H",		2, 8,	true, extended_instruction_84,
	"RES 0, L",		2, 8,	true, extended_instruction_85,
	"RES 0, (HL)",	2, 16,	true, extended_instruction_86,
	"RES 0, A",		2, 8,	true, extended_instruction_87,
	"RES 1, B",		2, 8,	true, extended_instruction_88,
	"RES 1, C",		2, 8,	true, extended_instruction_89,
	"RES 1, D",		2, 8,	true, extended_instruction_8a,
	"RES 1, E",		2, 8,	true, extended_instruction_8b,
	"RES 1, H",		2, 8,	true, extended_instruction_8c,
	"RES 1, L",		2, 8,	true, extended_instruction_8d,
	"RES 1, (HL)",	2, 16,	true, extended_instruction_8e,
	"RES 1, A",		2, 8,	true, extended_instruction_8f,
	"RES 2, B",		2, 8,	true, extended_instruction_90,
	"RES 2, C",		2, 8,	true, extended_instruction_91,
	"RES 2, D",		2, 8,	true, extended_instruction_92,
	"RES 2, E",		2, 8,	true, extended_instruction_93,
	"RES 2, H",		2, 8,	true, extended_instruction_94,
	"RES 2, L",		2, 8,	true, extended_instruction_95,
	"RES 2, (HL)",	2, 16,	true, extended_instruction_96,
	"RES 2, A",		2, 8,	true, extended_instruction_97,
	"RES 3, B",		2, 8,	true, extended_instruction_98,
	"RES 3, C",		2, 8,	true, extended_instruction_99,
	"RES 3, D",		2, 8,	true, extended_instruction_9a,
	"RES 3, E",		2, 8,	true, extended_instruction_9b,
	"RES 3, H",		2, 8,	true, extended_instruction_9c,
	"RES 3, L",		2, 8,	true, extended_instruction_9d,
	"RES 3, (HL)",  2, 16,	true, extended_instruction_9e,
	"RES 3, A",		2, 8,	true, extended_instruction_9f,
	"RES 4, B",		2, 8,	true, extended_instruction_a0,
	"RES 4, C",		2, 8,	true, extended_instruction_a1,
	"RES 4, D",		2, 8,	true, extended_instruction_a2,
	"RES 4, E",		2, 8,	true, extended_instruction_a3,
	"RES 4, H",		2, 8,	true, extended_instruction_a4,
	"RES 4, L",		2, 8,	true, extended_instruction_a5,
	"RES 4, (HL)",	2, 16,	true, extended_instruction_a6,
	"RES 4, A",		2, 8,	true, extended_instruction_a7,
	"RES 5, B",		2, 8,	true, extended_instruction_a8,
	"RES 5, C",		2, 8,	true, extended_instruction_a9,
	"RES 5, D",		2, 8,	true, extended_instruction_aa,
	"RES 5, E",		2, 8,	true, extended_instruction_ab,
	"RES 5, H",		2, 8,	true, extended_instruction_ac,
	"RES 5, L",		2, 8,	true, extended_instruction_ad,
	"RES 5, (HL)",	2, 16,	true, extended_instruction_ae,
	"RES 5, A",		2, 8,	true, extended_instruction_af,
	"RES 6, B",		2, 8,	true, extended_instruction_b0,
	"RES 6, C",		2, 8,	true, extended_instruction_b1,
	"RES 6, D",		2, 8,	true, extended_instruction_b2,
	"RES 6, E",		2, 8,	true, extended_instruction_b3,
	"RES 6, H",		2, 8,	true, extended_instruction_b4,
	"RES 6, L",		2, 8,	true, extended_instruction_b5,
	"RES 6, (HL)",	2, 16,	true, extended_instruction_b6,
	"RES 6, A",		2, 8,	true, extended_instruction_b7,
	"RES 7, B",		2, 8,	true, extended_instruction_b8,
	"RES 7, C",		2, 8,	true, extended_instruction_b9,
	"RES 7, D",		2, 8,	true, extended_instruction_ba,
	"RES 7, E",		2, 8,	true, extended_instruction_bb,
	"RES 7, H",		2, 8,	true, extended_instruction_bc,
	"RES 7, L",		2, 8,	true, extended_instruction_bd,
	"RES 7, (HL)",	2, 16,	true, extended_instruction_be,
	"RES 7, A",		2, 8,	true, extended_instruction_bf,
	"SET 0, B",		2, 8,	true, extended_instruction_c0,
	"SET 0, C",		2, 8,	true, extended_instruction_c1,
	"SET 0, D",		2, 8,	true, extended_instruction_c2,
	"SET 0, E",		2, 8,	true, extended_instruction_c3,
	"SET 0, H",		2, 8,	true, extended_instruction_c4,
	"SET 0, L",		2, 8,	true, extended_instruction_c5,
	"SET 0, (HL)",	2, 16,	true, extended_instruction_c6,
	"SET 0, A",		2, 8,	true, extended_instruction_c7,
	"SET 1, B",		2, 8,	true, extended_instruction_c8,
	"SET 1, C",		2, 8,	true, extended_instruction_c9,
	"SET 1, D",		2, 8,	true, extended_instruction_ca,
	"SET 1, E",		2, 8,	true, extended_instruction_cb,
	"SET 1, H",		2, 8,	true, extended_instruction_cc,
	"SET 1, L",		2, 8,	true, extended_instruction_cd,
	"SET 1, (HL)",	2, 16,	true, extended_instruction_ce,
	"SET 1, A",		2, 8,	true, extended_instruction_cf,
	"SET 2, B",		2, 8,	true, extended_instruction_d0,
	"SET 2, C",		2, 8,	true, extended_instruction_d1,
	"SET 2, D",		2, 8,	true, extended_instruction_d2,
	"SET 2, E",		2, 8,	true, extended_instruction_d3,
	"SET 2, H",		2, 8,	true, extended_instruction_d4,
	"SET 2, L",		2, 8,	true, extended_instruction_d5,
	"SET 2, (HL)",	2, 16,	true, extended_instruction_d6,
	"SET 2, A",		2, 8,	true, extended_instruction_d7,
	"SET 3, B",		2, 8,	true, extended_instruction_d8,
	"SET 3, C",		2, 8,	true, extended_instruction_d9,
	"SET 3, D",		2, 8,	true, extended_instruction_da,
	"SET 3, E",		2, 8,	true, extended_instruction_db,
	"SET 3, H",		2, 8,	true, extended_instruction_dc,
	"SET 3, L",		2, 8,	true, extended_instruction_dd,
	"SET 3, (HL)",	2, 16,	true, extended_instruction_de,
	"SET 3, A",		2, 8,	true, extended_instruction_df,
	"SET 4, B",		2, 8,	true, extended_instruction_e0,
	"SET 4, C",		2, 8,	true, extended_instruction_e1,
	"SET 4, D",		2, 8,	true, extended_instruction_e2,
	"SET 4, E",		2, 8,	true, extended_instruction_e3,
	"SET 4, H",		2, 8,	true, extended_instruction_e4,
	"SET 4, L",		2, 8,	true, extended_instruction_e5,
	"SET 4, (HL)",	2, 16,	true, extended_instruction_e6,
	"SET 4, A",		2, 8,	true, extended_instruction_e7,
	"SET 5, B",		2, 8,	true, extended_instruction_e8,
	"SET 5, C",		2, 8,	true, extended_instruction_e9,
	"SET 5, D",		2, 8,	true, extended_instruction_ea,
	"SET 5, E",		2, 8,	true, extended_instruction_eb,
	"SET 5, H",		2, 8,	true, extended_instruction_ec,
	"SET 5, L",		2, 8,	true, extended_instruction_ed,
	"SET 5, (HL)",	2, 16,	true, extended_instruction_ee,
	"SET 5, A",		2, 8,	true, extended_instruction_ef,
	"SET 6, B",		2, 8,	true, extended_instruction_f0,
	"SET 6, C",		2, 8,	true, extended_instruction_f1,
	"SET 6, D",		2, 8,	true, extended_instruction_f2,
	"SET 6, E",		2, 8,	true, extended_instruction_f3,
	"SET 6, H",		2, 8,	true, extended_instruction_f5,
	"SET 6, L",		2, 8,	true, extended_instruction_f6,
	"SET 6, (HL)",	2, 16,	true, extended_instruction_f7,
	"SET 7, B",		2, 8,	true, extended_instruction_f8,
	"SET 7, C",		2, 8,	true, extended_instruction_f9,
	"SET 7, D",		2, 8,	true, extended_instruction_fa,
	"SET 7, E",		2, 8,	true, extended_instruction_fb,
	"SET 7, H",		2, 8,	true, extended_instruction_fc,
	"SET 7, L",		2, 8,	true, extended_instruction_fd,
	"SET 7, (HL)",	2, 16,	true, extended_instruction_fe,
	"SET 7, A",		2, 8,	true, extended_instruction_ff
};